config/routes.rb
Unsnu::Application.routes.draw do
  devise_for :users
  root to: "static_pages#home"
  resources :boards, path: 'admin'

  resources :users, only: :show, shallow: true do
    resources :messages, only: :index
    resources :articles, only: :index
    resources :comments, only: :index
  end

  resources :messages, except: :index

  resources :tags, except: [:edit, :update]

  resources :comments, except: :index

  resources :boards, only: :show do
    resources :articles, shallow: true do
      get 'page/:page', action: :index, on: :collection
    end
  end

  resources :articles, except: :index do
    member do
      patch 'upvote', as: 'upvote', to: 'articles#upvote'
      patch 'downvote', as: 'downvote', to: 'articles#downvote'
    end
    resources :comments, shallow: true
  end

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :board
  belongs_to :user
	has_many :comments
  has_many :voted_users, foreign_key: 'article_id', class_name: 'ArticleVote'

  def page_num(options = {})
    column = options[:by] || :id
    order = options[:order] || :asc
    per = options[:per] || self.class.default_per_page

    operator = (order == :asc ? "<=" : ">=")
    (self.class.where("#{column} #{operator} ? AND board_id = ?", read_attribute(column), self.board_id).order("#{column} #{order}").count.to_f / per).ceil
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :auth_user

  # GET /articles
  # GET /articles.json
  def index
    @board = Board.find(params[:board_id])
    @articles = @board.articles.order("created_at DESC").page params[:page]
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    Article.increment_counter(:view_count, @article)
    @comment = Comment.new
    index = @article.page_num(by: :created_at, order: :desc)
    @articles = @article.board.articles.order("created_at DESC").page(index)
  end

  # GET /articles/new
  def new
    @article = Board.find(params[:board_id]).articles.new
  end

  # GET /articles/1/edit
  def edit
    auth_privilege
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.board.anonymous?
      @article.nickname = current_user.anonymous_nickname
    else
      @article.nickname = current_user.nickname
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    auth_privilege

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    unless already_voted?
      Article.increment_counter(:upvote, @article)
      vote = @article.voted_users.new(user_id: current_user.id)
      vote.save
      notice = "추천되었습니다."
    else
      notice = "이미 추천/반대하셨습니다."
    end

    respond_to do |format|
      format.html { redirect_to @article, notice: notice }
      format.json { render json: @article.upvote }
    end
  end

  def downvote
    unless already_voted?
      Article.increment_counter(:downvote, @article)
      vote = @article.voted_users.new(user_id: current_user.id)
      vote.save
      notice = "반대되었습니다"
    else
      notice = "이미 추천/반대하셨습니다."
    end

    respond_to do |format|
      format.html { redirect_to @article, notice: notice }
      format.json { render json: @article.downvote }
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    auth_privilege

    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :nickname, :content, :upvote, :downvote, :comment_count, :locked, :view_count, :board_id)
    end

    def auth_user
      unless current_user
        redirect_to root_path
      else
        unless current_user.anonymous_available_date == Date.today
          current_user.anonymous_nickname = SecureRandom.hex(4)
          current_user.anonymous_available_date = Date.today
          current_user.save
        end
      end
    end

    def auth_privilege
      unless current_user == @article.user || current_user.admin?
        redirect_to @article
      end
    end

    def already_voted?
      if @article.voted_users.where(user_id: current_user.id).present?
        true
      else
        false
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :board_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit '저장', class: 'btn btn-primary'

app/views/articles/_list.html.haml
%table.table
  %tr
    %th.hidden-xs #
    %th 제목
    %th.hidden-xs 추천
    %th 글쓴이
    %th.hidden-xs 날짜
    %th.hidden-xs 조회수
  - articles.each do |article|
    %tr
      %td.hidden-xs= article.id
      %td
        = link_to article.title, article
        = "[#{article.comment_count}]"
      %td.hidden-xs= article.upvote
      %td= article.nickname
      %td.hidden-xs= article.created_at.getlocal.strftime("%Y-%m-%d")
      %td.hidden-xs= article.view_count

.clearfix
  = link_to '글쓰기', new_board_article_path(board.id), class: 'btn btn-primary pull-right'
.text-center
  = paginate articles, params: { controller: :articles, action: :index, board_id: board.id, id: nil }

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h2= @board.name

= render partial: 'list', locals: { articles: @articles, board: @board }

app/views/articles/new.html.haml
%h1 글쓰기

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title.pull-left= @article.title
    %span.pull-right= @article.nickname
    .clearfix
  .panel-body
    .pull-right
      %span= @article.created_at.getlocal.strftime("%Y-%m-%d %H:%M:%S")
      %span
        = "up: #{@article.upvote}"
        = "down: #{@article.downvote}"
    .clearfix
    .content
      = @article.content
    .vote.text-center
      = link_to "추천", upvote_article_path(@article), id: "upvote", class: "btn btn-default", method: :patch
      = link_to "비추천", downvote_article_path(@article), id: "downvote", class: "btn btn-default", method: :patch
    - if @article.user == current_user || current_user.admin?
      .toolbox.pull-right
        = link_to "수정", edit_article_path(@article), class: "btn btn-default", id: "upvote"
        = link_to "삭제", @article, method: :delete, data: { confirm: "삭제하시겠습니까?" }, class: "btn btn-default", id: "downvote"
      .clearfix
    %ul
      - @article.comments.each do |comment|
        %li
          = "#{comment.nickname}: #{comment.content}"
          - if current_user == comment.user
            = link_to "x", comment, method: :delete, data: { confirm: "삭제하시겠습니까?" }
    = form_for @comment do |f|
      = f.hidden_field :article_id, value: @article.id
      = f.text_field :content
      = f.submit
= render partial: 'list', locals: { articles: @articles, board: @article.board }